framework:
    messenger:
      # transports:
      #       # https://symfony.com/doc/current/messenger.html#transport-configuration
      #       async: 'sync://'
      #       async_priority_high: 'sync://'